import { Spells } from '../../../store/types';

export const spells: Spells = {
  'Almighty Prod!': {
    name: 'Almighty Prod!',
    school: 'Amber',
    difficulty: 6,
    target: 'Friendly unit within 18"',
    duration: 'Until the target unit fails an ordered activation roll',
    effect:
      'When the target unit fails an ordered activation roll it may immediately reroll the test once. The spell ends immediately whether successful or not. The caster cannot target itself.',
    short: 'Target may reroll its next failed ordered activation roll.',
  },
  'Be Brave!': {
    name: 'Be Brave!',
    school: 'Amber',
    difficulty: 6,
    target: 'Friendly unit within 18"',
    duration: 'Until the end of your next activation phase',
    effect:
      'The target may reroll all failed Courage tests once per test. The caster cannot target itself.',
    short: 'Target may reroll failed Courage tests.',
  },
  'Take That You Rotter!': {
    name: 'Take That You Rotter!',
    school: 'Crimson',
    difficulty: 7,
    target: 'Enemy unit within 18"',
    duration: '1 immediate Shoot action',
    effect:
      'A magical ranged attack functioning as a Shoot action with Shoot value 5+, suffering -1 at over 12".',
    short: 'Grants a magical Shoot action (5+).',
  },
  'Utter Chaos!': {
    name: 'Utter Chaos!',
    school: 'Crimson',
    difficulty: 6,
    target: 'Any unit within 18"',
    duration: 'Until the end of your next activation phase',
    effect:
      'The target gains the Chaotic rule. Caster must provide the d12. Cannot target itself.',
    short: 'Target gains the Chaotic rule.',
  },
  'Heal Thee!': {
    name: 'Heal Thee!',
    school: 'Emerald',
    difficulty: 6,
    target: 'Friendly unit within 18" (not the caster)',
    duration: 'Immediate',
    effect:
      'Restores 1 Strength Point (max original value). On an 8+ the unit regains 2 Strength Points.',
    short: 'Restore 1 (2 on 8+) Strength Points to a friendly unit.',
  },
  'Sod-Off Spell!': {
    name: 'Sod-Off Spell!',
    school: 'Emerald',
    difficulty: 8,
    target: 'Any unit currently bespelled within 18"',
    duration: 'Immediate cancellation',
    effect: 'Cancels any spell currently affecting the target unit.',
    short: 'Cancels an active spell on a unit.',
  },
  'Superglue You!': {
    name: 'Superglue You!',
    school: 'Indigo',
    difficulty: 7,
    target: 'Self or any unit within 18"',
    duration: 'Until the end of your next activation phase',
    effect:
      'Target cannot move at all and forces enemies to retreat instead of retreating itself.',
    short: 'Target becomes immovable.',
  },
  'You Shall Not Pass!': {
    name: 'You Shall Not Pass!',
    school: 'Indigo',
    difficulty: 8,
    target:
      'A point on the table within 12" and line of sight, at least 3" from any unit',
    duration: 'Until the end of your next activation phase',
    effect:
      'Creates a 12" × 1" impassable barrier blocking LOS; cannot pass through or cast through it.',
    short: 'Creates a 12" impassable barrier.',
  },
  'Bog Thee!': {
    name: 'Bog Thee!',
    school: 'Jade',
    difficulty: 7,
    target: 'Enemy unit within 18"',
    duration: 'Until the end of your next activation phase',
    effect:
      'Target’s movement and combat count as rough terrain unless already in real rough terrain.',
    short: 'Target treats movement/combat as rough terrain.',
  },
  'Spring Heeled!': {
    name: 'Spring Heeled!',
    school: 'Jade',
    difficulty: 6,
    target: 'Self or friendly unit within 18"',
    duration: 'Until the end of your next activation phase',
    effect: 'Target does not halve its Move in rough terrain.',
    short: 'Target does not halve its Move in rough terrain.',
  },
  'You Have Wings!': {
    name: 'You Have Wings!',
    school: 'Jade',
    difficulty: 7,
    target: 'Self or friendly unit within 18"',
    duration: 'Until the end of your next activation phase',
    effect: 'The target gains the Flyer rule.',
    short: 'Target gains Flight.',
  },
  'Sharp Blades!': {
    name: 'Sharp Blades!',
    school: 'Magenta',
    difficulty: 7,
    target: 'Self or friendly unit within 18"',
    duration: 'Until the end of your next activation phase',
    effect: 'Target may reroll all failed Attack or Defence dice, even when Battered.',
    short: 'Reroll all failed Attack/Defence dice.',
  },
  'Sharp Darts!': {
    name: 'Sharp Darts!',
    school: 'Magenta',
    difficulty: 7,
    target: 'Self or friendly unit within 18"',
    duration: 'Until the end of your next activation phase',
    effect: 'Target may reroll all failed Shooting dice.',
    short: 'Reroll failed Shooting dice.',
  },
  'Stronger Shields!': {
    name: 'Stronger Shields!',
    school: 'Magenta',
    difficulty: 7,
    target: 'Self or friendly unit within 18"',
    duration: 'Until the end of your next activation phase',
    effect: 'Target’s Armour increases by 1.',
    short: 'Increase Armour by 1.',
  },
  'Dragons Breath!': {
    name: "Dragon's Breath!",
    school: 'Saffron',
    difficulty: 6,
    target: 'Self or any unit within 18"',
    duration: 'Until the end of your next activation phase',
    effect:
      'Target cannot Shoot or be Shot at; still moves and can be targeted by spells.',
    short: 'Target is immune to and cannot make Shooting attacks.',
  },
  'Go Wild!': {
    name: 'Go Wild!',
    school: 'Saffron',
    difficulty: 6,
    target: 'Self or friendly unit within 18"',
    duration: 'Until the end of your next activation phase',
    effect:
      'Target gains the Berserk rule; Berserk units at/below half strength regain Berserk.',
    short: 'Target gains Berserk (or regains it if weakened).',
  },
  'Teleport Thee!': {
    name: 'Teleport Thee!',
    school: 'Turquoise',
    difficulty: 7,
    target: 'Self or friendly unit within 12"',
    duration: 'Immediate',
    effect:
      'Move the target up to 12" ignoring activation; can cross impassible terrain; cannot be placed within 3" of units or off table or in impassable terrain.',
    short: 'Move a unit up to 12" instantly.',
  },
  'Transpose Thee!': {
    name: 'Transpose Thee!',
    school: 'Turquoise',
    difficulty: 8,
    target: 'Any two units within 12" of caster and within 12" of each other',
    duration: 'Immediate',
    effect:
      'The two target units swap places; they may be deployed as each unit\'s owning player wishes but must maintain unit cohesion and cannot be placed within 3" of any other unit. This does not count as the target units activation, and the Spell may target Battered units. The target units can be friends or enemies but the Spellcaster cannot target itself.',
    short: 'Swap positions of two units.',
  },
  'Befuddle Thee!': {
    name: 'Befuddle Thee!',
    school: 'Violet',
    difficulty: 8,
    target: 'Enemy unit within 18"',
    duration: 'Until the target unit Rallies',
    effect: 'Automatically Batters a non-Battered, non-Undead target.',
    short: 'Automatically Batters a valid enemy unit.',
  },
  'Curse Thee!': {
    name: 'Curse Thee!',
    school: 'Violet',
    difficulty: 7,
    target: 'Enemy unit within 18"',
    duration: 'Until the end of your next activation phase',
    effect: 'Target gains the Cursed rule.',
    short: 'Target gains the Cursed rule.',
  },
};
