import { Units } from '../../store/types';

export const unitsData: Units = {
  Unit: {
    name: 'Unit',
    type: 'foot',
    points: 0,
    stats: {
      attack: 0,
      move: 0,
      shoot: 0,
      courage: 0,
      armor: 0,
      attackValue: 0,
      defenceValue: 0,
      shootValue: 0,
      shootRange: 0,
      movement: 0,
      strengthPoints: 0,
    },
    rules: [],
    options: {},
    fantasticalRules: [],
  },
  'Elite Riders': {
    name: 'Elite Riders',
    type: 'mounted',
    points: 6,
    stats: {
      attack: 5,
      move: 7,
      shoot: 0,
      courage: 3,
      armor: 4,
      attackValue: 3,
      defenceValue: 5,
      shootValue: 0,
      shootRange: 0,
      movement: 10,
      strengthPoints: 6,
    },
    rules: ['Wild Charge', 'Counter-charge'],
    options: {
      'Mounted missiles': {
        name: 'Mounted missiles',
        points: 2,
        description:
          'Wild Charge and Counter-charge are removed and replaced with Shoot 6+/Range 12" hitting on 5+.',
        short: 'Shoot 6+, shoot value 5+/12". Remove Wild Charge, Counter-charge',
        remove: ['Wild Charge', 'Counter-charge'],
        setStats: {
          shoot: 6,
          shootValue: 5,
          shootRange: 12,
        },
      },
      'Level Headed': {
        name: 'Level Headed',
        points: 2,
        description: 'Remove Wild Charge and change Move to 5+.',
        short: 'Remove Wild Charge, Move 5+.',
        remove: ['Wild Charge'],
        setStats: {
          move: 5,
        },
      },
    },
    fantasticalRules: [],
  },
  'Heavy Riders': {
    name: 'Heavy Riders',
    type: 'mounted',
    points: 4,
    stats: {
      attack: 5,
      move: 5,
      shoot: 0,
      courage: 4,
      armor: 3,
      attackValue: 4,
      defenceValue: 5,
      shootValue: 0,
      shootRange: 0,
      movement: 10,
      strengthPoints: 6,
    },
    rules: ['Counter-charge'],
    options: {
      'Mounted missiles': {
        name: 'Mounted missiles',
        points: 1,
        description: 'Add Shoot 6+/Range 12" hitting on 5+.',
        short: 'Shoot 6+, shoot value 5+/12".',
        setStats: {
          shoot: 6,
          shootValue: 5,
          shootRange: 12,
        },
      },
      Chariots: {
        name: 'Chariots',
        points: 2,
        description: 'May not enter rough terrain. armor is increased to 4.',
        short: "Can't enter rough terrain, armor 4.",
        add: ['Chariots'],
        setStats: {
          armor: 4,
        },
      },
    },
    fantasticalRules: [],
  },
  'Light Riders': {
    name: 'Light Riders',
    type: 'mounted',
    points: 4,
    stats: {
      attack: 7,
      move: 5,
      shoot: 6,
      courage: 5,
      armor: 3,
      attackValue: 5,
      defenceValue: 6,
      shootValue: 5,
      shootRange: 12,
      movement: 12,
      strengthPoints: 6,
    },
    rules: ['Skirmish', 'Evade'],
    options: {
      'Short range missiles': {
        name: 'Short range missiles',
        points: -1,
        description: 'Range reduced to 6".',
        short: 'Range reduced to 6".',
        setStats: {
          shootRange: 6,
        },
      },
    },
    fantasticalRules: [],
  },
  'Greater Warbeasts': {
    name: 'Greater Warbeasts',
    type: 'mounted',
    points: 6,
    stats: {
      attack: 5,
      move: 6,
      shoot: 0,
      courage: 3,
      armor: 4,
      attackValue: 3,
      defenceValue: 6,
      shootValue: 0,
      shootRange: 0,
      movement: 10,
      strengthPoints: 6,
    },
    rules: ['Ranger', 'Wild Charge'],
    options: {
      'Flame or Spore Attack': {
        name: 'Flame or Spore Attack',
        points: 2,
        description:
          'Wild Charge is removed and replaced with Shoot 6+/Range 12" hitting on 5+.',
        short: 'Shoot 6+, shoot value 5+/12", remove Wild Charge',
        setStats: {
          shoot: 6,
          shootValue: 5,
          shootRange: 12,
        },
        remove: ['Wild Charge'],
      },
      Ponderous: {
        name: 'Ponderous',
        points: 1,
        description: 'Remove Wild Charge.',
        short: 'Remove Wild Charge.',
        remove: ['Wild Charge'],
      },
      Cunning: {
        name: 'Cunning',
        points: 2,
        description: 'Defence Value becomes 5+.',
        short: 'Defence Value 5+.',
        setStats: {
          defenceValue: 5,
        },
      },
    },
    fantasticalRules: [],
  },
  'Lesser Warbeasts': {
    name: 'Lesser Warbeasts',
    type: 'mounted',
    points: 4,
    stats: {
      attack: 5,
      move: 6,
      shoot: 0,
      courage: 4,
      armor: 3,
      attackValue: 4,
      defenceValue: 6,
      shootValue: 0,
      shootRange: 0,
      movement: 12,
      strengthPoints: 6,
    },
    rules: ['Ranger', 'Wild Charge', 'Fleet Footed'],
    options: {
      'Flame or Spore Attack': {
        name: 'Flame or Spore Attack',
        points: 2,
        description:
          'Wild Charge is removed and replaced with Shoot 6+/Range 12" hitting on 5+.',
        short: 'Shoot 6+, shoot value 5+/12", remove Wild Charge',
        setStats: {
          shoot: 6,
          shootValue: 5,
          shootRange: 12,
        },
        remove: ['Wild Charge'],
      },
      Cunning: {
        name: 'Cunning',
        points: 2,
        description: 'Defence Value becomes 5+.',
        short: 'Defence Value 5+.',
        setStats: {
          defenceValue: 5,
        },
      },
    },
    fantasticalRules: [],
  },
  'Elite Foot': {
    name: 'Elite Foot',
    type: 'foot',
    points: 6,
    stats: {
      attack: 5,
      move: 5,
      shoot: 0,
      courage: 3,
      armor: 4,
      attackValue: 3,
      defenceValue: 4,
      shootValue: 0,
      shootRange: 0,
      movement: 6,
      strengthPoints: 6,
    },
    rules: ['Ranger'],
    options: {
      Missiles: {
        name: 'Missiles',
        points: 2,
        description: 'Add Shoot 6+/Range 18" hitting on 5+.',
        short: 'Shoot 6+, shoot value 5+/18".',
        setStats: {
          shoot: 6,
          shootValue: 5,
          shootRange: 18,
        },
      },
    },
    fantasticalRules: [],
  },
  'Heavy Foot': {
    name: 'Heavy Foot',
    type: 'foot',
    points: 4,
    stats: {
      attack: 6,
      move: 5,
      shoot: 0,
      courage: 4,
      armor: 3,
      attackValue: 5,
      defenceValue: 4,
      shootValue: 0,
      shootRange: 0,
      movement: 6,
      strengthPoints: 12,
    },
    rules: ['Wall of Spears'],
    options: {
      Offensive: {
        name: 'Offensive',
        points: 2,
        description:
          'Attack Value becomes 4+. The unit may no longer form a Wall of Spears.',
        short: 'Attack Value 4+. Remove Wall of Spears.',
        setStats: {
          attackValue: 4,
        },
        remove: ['Wall of Spears'],
      },
    },
    fantasticalRules: [],
  },
  'Light Foot': {
    name: 'Light Foot',
    type: 'foot',
    points: 3,
    stats: {
      attack: 6,
      move: 5,
      shoot: 0,
      courage: 4,
      armor: 2,
      attackValue: 5,
      defenceValue: 4,
      shootValue: 0,
      shootRange: 0,
      movement: 8,
      strengthPoints: 12,
    },
    rules: ['Wall of Spears'],
    options: {
      Offensive: {
        name: 'Offensive',
        points: 2,
        description:
          'Attack Value becomes 4+. The unit may no longer form a Wall of Spears.',
        short: 'Attack Value 4+. Remove Wall of Spears.',
        setStats: {
          attackValue: 4,
        },
        remove: ['Wall of Spears'],
      },
      'Short range missiles': {
        name: 'Short range missiles',
        points: 1,
        description: 'Shoot 6+/Range 6" hitting on 5+.',
        short: 'Shoot 6+, shoot value 5+/6".',
        setStats: {
          shoot: 6,
          shootValue: 5,
          shootRange: 6,
        },
      },
      'Mixed Weapons': {
        name: 'Mixed Weapons',
        points: 2,
        description: 'Shoot 6+, Range 12" hitting on 5+. Remove Wall of Spears.',
        short: 'Shoot 6+, shoot value 5+/6". Remove Wall of Spears.',
        setStats: {
          shoot: 6,
          shootValue: 5,
          shootRange: 12,
        },
        remove: ['Wall of Spears'],
      },
    },
    fantasticalRules: [],
  },
  'Bellicose Foot': {
    name: 'Bellicose Foot',
    type: 'foot',
    points: 4,
    stats: {
      attack: 5,
      move: 6,
      shoot: 0,
      courage: 4,
      armor: 2,
      attackValue: 3,
      defenceValue: 6,
      shootValue: 0,
      shootRange: 0,
      movement: 8,
      strengthPoints: 12,
    },
    rules: ['Ranger', 'Wild Charge', 'Counter-charge vs. foot', 'Fleet Footed'],
    options: {
      'Terrifically Shiny armor': {
        name: 'Terrifically Shiny armor',
        points: 2,
        description: 'Armor becomes 3.',
        short: 'Armor 3.',
        setStats: {
          armor: 3,
        },
      },
    },
    fantasticalRules: [],
  },
  'Heavy Missiles': {
    name: 'Heavy Missiles',
    type: 'foot',
    points: 4,
    stats: {
      attack: 7,
      move: 6,
      shoot: 7,
      courage: 4,
      armor: 2,
      attackValue: 6,
      defenceValue: 5,
      shootValue: 4,
      shootRange: 18,
      movement: 6,
      strengthPoints: 12,
    },
    rules: [],
    options: {
      'Weighty Projectiles': {
        name: 'Weighty Projectiles',
        points: -1,
        description: 'Range reduced to 12".',
        short: 'Range reduced to 12".',
        setStats: {
          shootRange: 12,
        },
      },
    },
    fantasticalRules: [],
  },
  'Light Missiles': {
    name: 'Light Missiles',
    type: 'foot',
    points: 4,
    stats: {
      attack: 7,
      move: 6,
      shoot: 6,
      courage: 4,
      armor: 2,
      attackValue: 6,
      defenceValue: 5,
      shootValue: 5,
      shootRange: 18,
      movement: 6,
      strengthPoints: 12,
    },
    rules: [],
    options: {
      Sharpshooter: {
        name: 'Sharpshooter',
        points: 2,
        description: 'Shoot Value becomes 4+.',
        short: 'Shoot Value 4+.',
        setStats: {
          shootValue: 4,
        },
      },
    },
    fantasticalRules: [],
  },
  Scouts: {
    name: 'Scouts',
    type: 'foot',
    points: 2,
    stats: {
      attack: 7,
      move: 5,
      shoot: 7,
      courage: 5,
      armor: 1,
      attackValue: 6,
      defenceValue: 6,
      shootValue: 5,
      shootRange: 12,
      movement: 8,
      strengthPoints: 6,
    },
    rules: ['Hard to target', 'Skirmish', 'Evade', 'Fleet Footed'],
    options: {},
    fantasticalRules: [],
  },
  'Ravenous Hordes': {
    name: 'Ravenous Hordes',
    type: 'foot',
    points: 1,
    stats: {
      attack: 7,
      move: 6,
      shoot: 0,
      courage: 5,
      armor: 1,
      attackValue: 6,
      defenceValue: 6,
      shootValue: 0,
      shootRange: 0,
      movement: 6,
      strengthPoints: 12,
    },
    rules: [],
    options: {},
    fantasticalRules: [],
  },
};
